import { AppLang } from './i18n.service';

/** Title/excerpt only — SEO meta without pulling full blog bodies into the main bundle. */
export type BlogSeoMeta = { title: string; excerpt: string };

const BLOG_SEO: Record<string, Record<AppLang, BlogSeoMeta>> = {
  'follownet-features-overview': {
    en: { title: 'FollowNet features: Smart Connect, protocols, DNS, Auto-connect, and more', excerpt: 'A full tour of what ships in the iOS app and Chrome extension — protocols, Smart Connect, Auto-connect, DNS, Network Profiles, widgets, Speed Test, and Free vs Premium.' },
    ru: { title: 'Возможности FollowNet: Smart Connect, протоколы, DNS, автоподключение и остальное', excerpt: 'Полный обзор того, что есть в iOS-приложении и Chrome: протоколы, Smart Connect, автоподключение, DNS, профили сети, виджеты, Speed Test и Free vs Premium.' },
    uk: { title: 'Функції FollowNet: Smart Connect, протоколи, DNS, автоматичне підключення тощо', excerpt: 'Повний огляд того, що постачається в додатку для iOS і розширенні для Chrome — протоколи, Smart Connect, автоматичне підключення, DNS, мережеві профілі, віджети, перевірка швидкості та Free vs Premium.' },
    de: { title: 'FollowNet-Funktionen: Smart Connect, Protokolle, DNS, Auto-Connect und mehr', excerpt: 'Eine vollständige Übersicht über den Lieferumfang der iOS-App und der Chrome-Erweiterung – Protokolle, Smart Connect, Auto-Connect, DNS, Netzwerkprofile, Widgets, Geschwindigkeitstest und Free vs. Premium.' },
    es: { title: 'Funciones de FollowNet: Smart Connect, protocolos, DNS, conexión automática y más', excerpt: 'Un recorrido completo por lo que se incluye en la aplicación iOS y la extensión de Chrome: protocolos, Smart Connect, conexión automática, DNS, perfiles de red, widgets, prueba de velocidad y Free vs Premium.' },
    fr: { title: 'Fonctionnalités FollowNet : Smart Connect, protocoles, DNS, connexion automatique, etc.', excerpt: 'Une visite complète de ce qui est fourni dans l\'application iOS et l\'extension Chrome : protocoles, Smart Connect, connexion automatique, DNS, profils réseau, widgets, test de vitesse et Free vs Premium.' },
    pt: { title: 'Recursos do FollowNet: Smart Connect, protocolos, DNS, conexão automática e muito mais', excerpt: 'Um tour completo do que vem no aplicativo iOS e na extensão do Chrome – protocolos, Smart Connect, conexão automática, DNS, perfis de rede, widgets, teste de velocidade e gratuito x premium.' },
  },
  'free-vs-premium-honest': {
    en: { title: 'Free vs Premium without the fine print theater', excerpt: 'What FollowNet Free actually includes, when Premium is worth it, how weekly traffic works, and what we refuse to hide in a nine-point footer.' },
    ru: { title: 'Free и Premium без мелкого шрифта', excerpt: 'Что реально даёт FollowNet Free, когда нужен Premium, как работает недельный лимит и что мы не прячем в девятистрочный футер.' },
    uk: { title: 'Free і Premium без дрібного шрифту', excerpt: 'Що насправді дає FollowNet Free, коли варто брати Premium, як працює тижневий ліміт і що ми не ховаємо в дев’ятирядковий футер.' },
    de: { title: 'Free vs. Premium ohne Kleingedrucktes', excerpt: 'Was FollowNet Free wirklich enthält, wann Premium sinnvoll ist, wie der Wochen-Traffic funktioniert und was wir nicht in einer 9-Punkte-Fußzeile verstecken.' },
    es: { title: 'Gratis vs Premium sin letra pequeña', excerpt: 'Qué incluye realmente FollowNet Free, cuándo vale Premium, cómo funciona el tráfico semanal y qué nos negamos a ocultar en un pie de 9 puntos.' },
    fr: { title: 'Gratuit vs Premium sans le théâtre des petits caractères', excerpt: 'Ce que FollowNet Free inclut vraiment, quand Premium vaut le coup, comment marche le trafic hebdomadaire, et ce que nous refusons de cacher.' },
    pt: { title: 'Gratuito vs Premium sem as letras miúdas', excerpt: 'O que o FollowNet Free realmente inclui, quando o Premium vale a pena, como funciona o tráfego semanal e o que nos recusamos a esconder.' },
  },
  'which-protocol-when': {
    en: { title: 'WireGuard, AmneziaWG, IKEv2, Hysteria2 — which protocol when', excerpt: 'A practical map of FollowNet protocols on iOS: speed, stability, and what to use when a network fights VPNs.' },
    ru: { title: 'WireGuard, AmneziaWG, IKEv2, Hysteria2 — какой протокол когда', excerpt: 'Практичная карта протоколов FollowNet на iOS: скорость, стабильность и что включать, когда сеть душит VPN.' },
    uk: { title: 'WireGuard, AmneziaWG, IKEv2, Hysteria2 — який протокол коли', excerpt: 'Практична карта протоколів FollowNet на iOS: швидкість, стабільність і що вмикати, коли мережа душить VPN.' },
    de: { title: 'WireGuard, AmneziaWG, IKEv2, Hysteria2 – welches Protokoll wann', excerpt: 'Eine praktische Karte der FollowNet-Protokolle auf iOS: Geschwindigkeit, Stabilität und was zu tun ist, wenn ein Netz VPNs bekämpft.' },
    es: { title: 'WireGuard, AmneziaWG, IKEv2, Hysteria2: qué protocolo y cuándo', excerpt: 'Un mapa práctico de los protocolos FollowNet en iOS: velocidad, estabilidad y qué usar cuando una red pelea con las VPN.' },
    fr: { title: 'WireGuard, AmneziaWG, IKEv2, Hysteria2 — quel protocole quand', excerpt: 'Une carte pratique des protocoles FollowNet sur iOS : vitesse, stabilité et quoi utiliser quand un réseau combat les VPN.' },
    pt: { title: 'WireGuard, AmneziaWG, IKEv2, Hysteria2 — qual protocolo quando', excerpt: 'Um mapa prático dos protocolos FollowNet no iOS: velocidade, estabilidade e o que usar quando uma rede luta contra VPNs.' },
  },
  'chrome-extension': {
    en: { title: 'FollowNet for Chrome is live', excerpt: 'The same account and a browser proxy for desktop Chrome — what the extension does today and where its protection ends.' },
    ru: { title: 'FollowNet для Chrome уже доступен', excerpt: 'Тот же аккаунт и прокси для Chrome на компьютере — что расширение умеет сейчас и где заканчивается его защита.' },
    uk: { title: 'FollowNet для Chrome працює', excerpt: 'Той самий обліковий запис і проксі-сервер веб-переглядача для комп’ютерного Chrome — що робить розширення сьогодні та де закінчується його захист.' },
    de: { title: 'FollowNet für Chrome ist live', excerpt: 'Das gleiche Konto und ein Browser-Proxy für Desktop-Chrome – was die Erweiterung heute macht und wo ihr Schutz endet.' },
    es: { title: 'FollowNet para Chrome ya está disponible', excerpt: 'La misma cuenta y un navegador proxy para Chrome de escritorio: qué hace la extensión hoy y dónde termina su protección.' },
    fr: { title: 'FollowNet pour Chrome est en ligne', excerpt: 'Le même compte et un proxy de navigateur pour Chrome de bureau : ce que fait l\'extension aujourd\'hui et où s\'arrête sa protection.' },
    pt: { title: 'FollowNet para Chrome está ativo', excerpt: 'A mesma conta e um proxy de navegador para desktop Chrome – o que a extensão faz hoje e onde termina sua proteção.' },
  },
  'smart-connect-explained': {
    en: { title: 'Smart Connect: how FollowNet picks a path', excerpt: 'Automatic protocol selection is not magic — here is what it optimizes for and when to override it.' },
    ru: { title: 'Smart Connect: как FollowNet выбирает путь', excerpt: 'Автовыбор протокола — не магия. Что он оптимизирует и когда лучше переключить вручную.' },
    uk: { title: 'Smart Connect: як FollowNet вибирає шлях', excerpt: 'Автоматичний вибір протоколу — це не магія — ось для чого він оптимізується та коли його можна змінити.' },
    de: { title: 'Smart Connect: Wie FollowNet einen Weg wählt', excerpt: 'Die automatische Protokollauswahl ist keine Zauberei – hier erfahren Sie, wofür sie optimiert wird und wann sie außer Kraft gesetzt werden sollte.' },
    es: { title: 'Smart Connect: cómo FollowNet elige un camino', excerpt: 'La selección automática de protocolos no es mágica: esto es para qué se optimiza y cuándo anularla.' },
    fr: { title: 'Smart Connect : comment FollowNet choisit un chemin', excerpt: 'La sélection automatique du protocole n’est pas magique : voici ce pour quoi elle est optimisée et quand la remplacer.' },
    pt: { title: 'Smart Connect: como a FollowNet escolhe um caminho', excerpt: 'A seleção automática de protocolo não é mágica – aqui está o que ela otimiza e quando substituí-la.' },
  },
  'ios-widgets-vpn': {
    en: { title: 'iOS widgets for FollowNet: status without opening the app', excerpt: 'Home Screen widgets show connection state at a glance — how they fit the one-tap VPN habit on iPhone.' },
    ru: { title: 'Виджеты FollowNet на iOS: статус без открытия приложения', excerpt: 'Виджеты на Home Screen показывают состояние туннеля — как они вписываются в привычку VPN в один тап.' },
    uk: { title: 'Віджети iOS для FollowNet: статус без відкриття програми', excerpt: 'Віджети на головному екрані миттєво показують стан з’єднання — як вони відповідають звичці VPN одним дотиком на iPhone.' },
    de: { title: 'iOS-Widgets für FollowNet: Status ohne Öffnen der App', excerpt: 'Widgets auf dem Startbildschirm zeigen den Verbindungsstatus auf einen Blick – wie sie zur One-Tap-VPN-Gewohnheit auf dem iPhone passen.' },
    es: { title: 'Widgets de iOS para FollowNet: estado sin abrir la aplicación', excerpt: 'Los widgets de la pantalla de inicio muestran el estado de la conexión de un vistazo: cómo se adaptan al hábito de VPN de un solo toque en el iPhone.' },
    fr: { title: 'Widgets iOS pour FollowNet : statut sans ouvrir l\'application', excerpt: 'Les widgets de l’écran d’accueil affichent l’état de la connexion en un coup d’œil – comment ils s’adaptent à l’habitude VPN en un clic sur iPhone.' },
    pt: { title: 'Widgets iOS para FollowNet: status sem abrir o aplicativo', excerpt: 'Os widgets da tela inicial mostram rapidamente o estado da conexão – como eles se adaptam ao hábito VPN de um toque no iPhone.' },
  },
  'dns-profiles-explained': {
    en: { title: 'DNS profiles in FollowNet: Quad9, Cloudflare, and when to switch', excerpt: 'Custom DNS does not replace VPN encryption — here is how presets work on iOS and what they actually change.' },
    ru: { title: 'DNS-профили в FollowNet: Quad9, Cloudflare и когда переключать', excerpt: 'Свой DNS не заменяет шифрование VPN — как работают пресеты на iOS и что они реально меняют.' },
    uk: { title: 'Профілі DNS у FollowNet: Quad9, Cloudflare та час перемикання', excerpt: 'Спеціальний DNS не замінює шифрування VPN — ось як працюють попередні налаштування в iOS і що вони насправді змінюють.' },
    de: { title: 'DNS-Profile in FollowNet: Quad9, Cloudflare und wann man wechseln sollte', excerpt: 'Benutzerdefiniertes DNS ersetzt keine VPN-Verschlüsselung – hier erfahren Sie, wie Voreinstellungen unter iOS funktionieren und was sie tatsächlich ändern.' },
    es: { title: 'Perfiles DNS en FollowNet: Quad9, Cloudflare y cuándo cambiar', excerpt: 'El DNS personalizado no reemplaza el cifrado VPN: así es como funcionan los ajustes preestablecidos en iOS y qué cambian realmente.' },
    fr: { title: 'Profils DNS dans FollowNet : Quad9, Cloudflare et quand changer', excerpt: 'Le DNS personnalisé ne remplace pas le cryptage VPN. Voici comment les préréglages fonctionnent sur iOS et ce qu\'ils modifient réellement.' },
    pt: { title: 'Perfis DNS no FollowNet: Quad9, Cloudflare e quando mudar', excerpt: 'O DNS personalizado não substitui a criptografia VPN – veja como as predefinições funcionam no iOS e o que elas realmente mudam.' },
  },
  'auto-connect-wifi-lte': {
    en: { title: 'Auto-connect on Wi‑Fi vs LTE: which mode to pick', excerpt: 'Disabled, Wi‑Fi Only, LTE Only, or Always — a practical guide so VPN starts when you need it and stays quiet at home.' },
    ru: { title: 'Автоподключение Wi‑Fi vs LTE: какой режим выбрать', excerpt: 'Выключено, только Wi‑Fi, только LTE или всегда — практичный гайд, чтобы VPN включался когда нужно и не мешал дома.' },
    uk: { title: 'Автоматичне підключення через Wi‑Fi чи LTE: який режим вибрати', excerpt: 'Вимкнено, лише Wi‑Fi, лише LTE або завжди — практичний посібник, щоб VPN запускався, коли вам це потрібно, і залишався тихим удома.' },
    de: { title: 'Automatische Verbindung über WLAN vs. LTE: Welcher Modus soll ausgewählt werden?', excerpt: 'Deaktiviert, Nur WLAN, Nur LTE oder Immer – eine praktische Anleitung, damit VPN startet, wenn Sie es brauchen, und zu Hause ruhig bleibt.' },
    es: { title: 'Conexión automática en Wi‑Fi frente a LTE: qué modo elegir', excerpt: 'Deshabilitado, Solo Wi‑Fi, Solo LTE o Siempre: una guía práctica para que la VPN se inicie cuando la necesites y permanezca silenciosa en casa.' },
    fr: { title: 'Connexion automatique sur Wi‑Fi vs LTE : quel mode choisir', excerpt: 'Désactivé, Wi‑Fi uniquement, LTE uniquement ou Toujours : un guide pratique pour que le VPN démarre lorsque vous en avez besoin et reste silencieux à la maison.' },
    pt: { title: 'Conexão automática em Wi-Fi vs LTE: qual modo escolher', excerpt: 'Desativado, Somente Wi‑Fi, Somente LTE ou Sempre — um guia prático para que a VPN seja iniciada quando você precisar e permaneça silenciosa em casa.' },
  },
  'public-wifi-risks': {
    en: { title: 'Public Wi‑Fi risks on iPhone — what VPN fixes and what it does not', excerpt: 'Airports and cafés are convenient. Here is the honest threat model for FollowNet users on shared hotspots.' },
    ru: { title: 'Риски публичного Wi‑Fi на iPhone — что чинит VPN и чего нет', excerpt: 'Аэропорты и кафе удобны. Честная модель угроз для пользователей FollowNet в общих точках доступа.' },
    uk: { title: 'Ризики публічного Wi‑Fi на iPhone — що VPN виправляє, а що ні', excerpt: 'Аеропорти та кафе зручні. Ось чесна модель загроз для користувачів FollowNet у спільних точках доступу.' },
    de: { title: 'Risiken durch öffentliches WLAN auf dem iPhone – was VPN behebt und was nicht', excerpt: 'Flughäfen und Cafés sind praktisch. Hier ist das ehrliche Bedrohungsmodell für FollowNet-Benutzer an gemeinsam genutzten Hotspots.' },
    es: { title: 'Riesgos del Wi‑Fi público en el iPhone: qué soluciona la VPN y qué no', excerpt: 'Los aeropuertos y cafeterías son convenientes. Este es el modelo de amenaza honesto para los usuarios de FollowNet en puntos de acceso compartidos.' },
    fr: { title: 'Risques liés au Wi-Fi public sur iPhone : quels VPN corrigent et ce qu\'il ne corrige pas', excerpt: 'Les aéroports et les cafés sont pratiques. Voici le modèle de menace honnête pour les utilisateurs de FollowNet sur les hotspots partagés.' },
    pt: { title: 'Riscos de Wi-Fi público no iPhone – o que a VPN corrige e o que não corrige', excerpt: 'Aeroportos e cafés são convenientes. Aqui está o modelo de ameaça honesto para usuários do FollowNet em pontos de acesso compartilhados.' },
  },
  'travel-vpn-roaming': {
    en: { title: 'Travel roaming with FollowNet: SIMs, hotels, and Smart Connect', excerpt: 'How to prepare before you fly, what to expect on foreign carriers, and when Premium locations matter.' },
    ru: { title: 'Роуминг с FollowNet: SIM, отели и Smart Connect', excerpt: 'Как подготовиться до вылета, чего ждать у зарубежных операторов и когда важны Premium-локации.' },
    uk: { title: 'Подорожуйте в роумінгу з FollowNet: SIM-карти, готелі та Smart Connect', excerpt: 'Як підготуватися до польоту, чого очікувати від іноземних перевізників і коли місцезнаходження Premium має значення.' },
    de: { title: 'Reiseroaming mit FollowNet: SIMs, Hotels und Smart Connect', excerpt: 'Wie Sie sich vor Ihrem Flug vorbereiten, was Sie bei ausländischen Fluggesellschaften erwartet und wann Premium-Standorte wichtig sind.' },
    es: { title: 'Viaja en roaming con FollowNet: SIM, hoteles y Smart Connect', excerpt: 'Cómo prepararse antes de volar, qué esperar de las aerolíneas extranjeras y cuándo son importantes las ubicaciones Premium.' },
    fr: { title: 'Itinérance de voyage avec FollowNet : cartes SIM, hôtels et Smart Connect', excerpt: 'Comment se préparer avant de prendre l\'avion, à quoi s\'attendre sur les transporteurs étrangers et quand les emplacements Premium sont importants.' },
    pt: { title: 'Roaming de viagens com FollowNet: SIMs, hotéis e Smart Connect', excerpt: 'Como se preparar antes de voar, o que esperar de companhias aéreas estrangeiras e quando as localizações Premium são importantes.' },
  },
  'hysteria2-on-ios': {
    en: { title: 'Hysteria2 on iOS in FollowNet: when lossy networks need a different path', excerpt: 'Why FollowNet ships Hysteria2 alongside WireGuard, IKEv2, and AmneziaWG — and when Smart Connect should pick it.' },
    ru: { title: 'Hysteria2 на iOS в FollowNet: когда плохим сетям нужен другой путь', excerpt: 'Зачем FollowNet держит Hysteria2 рядом с WireGuard, IKEv2 и AmneziaWG — и когда Smart Connect должен его выбрать.' },
    uk: { title: 'Hysteria2 на iOS у FollowNet: коли мережі з втратами потребують іншого шляху', excerpt: 'Чому FollowNet постачає Hysteria2 поряд з WireGuard, IKEv2 і AmneziaWG — і коли Smart Connect має вибрати її.' },
    de: { title: 'Hysteria2 auf iOS in FollowNet: Wenn verlustbehaftete Netzwerke einen anderen Pfad benötigen', excerpt: 'Warum FollowNet Hysteria2 zusammen mit WireGuard, IKEv2 und AmneziaWG anbietet – und wann Smart Connect sich dafür entscheiden sollte.' },
    es: { title: 'Hysteria2 en iOS en FollowNet: cuando las redes con pérdidas necesitan un camino diferente', excerpt: 'Por qué FollowNet envía Hysteria2 junto con WireGuard, IKEv2 y AmneziaWG, y cuándo Smart Connect debería elegirlo.' },
    fr: { title: 'Hysteria2 sur iOS dans FollowNet : quand les réseaux avec perte ont besoin d\'un chemin différent', excerpt: 'Pourquoi FollowNet livre Hysteria2 aux côtés de WireGuard, IKEv2 et AmneziaWG – et quand Smart Connect devrait le choisir.' },
    pt: { title: 'Hysteria2 no iOS no FollowNet: quando redes com perdas precisam de um caminho diferente', excerpt: 'Por que a FollowNet envia Hysteria2 junto com WireGuard, IKEv2 e AmneziaWG – e quando o Smart Connect deve escolhê-lo.' },
  },
  'passwordless-login': {
    en: { title: 'Passwordless login in FollowNet: email codes instead of another password', excerpt: 'Why FollowNet uses email verification codes on iOS and Chrome — and what that means for account security.' },
    ru: { title: 'Вход без пароля в FollowNet: email-коды вместо ещё одного пароля', excerpt: 'Почему FollowNet на iOS и в Chrome использует коды на почту — и что это значит для безопасности аккаунта.' },
    uk: { title: 'Вхід без пароля у FollowNet: коди електронної пошти замість іншого пароля', excerpt: 'Чому FollowNet використовує коди підтвердження електронної пошти в iOS і Chrome — і що це означає для безпеки облікового запису.' },
    de: { title: 'Passwortloses Login in FollowNet: E-Mail-Codes anstelle eines anderen Passworts', excerpt: 'Warum FollowNet E-Mail-Bestätigungscodes auf iOS und Chrome verwendet – und was das für die Kontosicherheit bedeutet.' },
    es: { title: 'Inicio de sesión sin contraseña en FollowNet: códigos de correo electrónico en lugar de otra contraseña', excerpt: 'Por qué FollowNet utiliza códigos de verificación de correo electrónico en iOS y Chrome, y qué significa eso para la seguridad de la cuenta.' },
    fr: { title: 'Connexion sans mot de passe dans FollowNet : codes e-mail au lieu d\'un autre mot de passe', excerpt: 'Pourquoi FollowNet utilise des codes de vérification de courrier électronique sur iOS et Chrome – et ce que cela signifie pour la sécurité des comptes.' },
    pt: { title: 'Login sem senha no FollowNet: códigos de e-mail em vez de outra senha', excerpt: 'Por que a FollowNet usa códigos de verificação de e-mail no iOS e no Chrome — e o que isso significa para a segurança da conta.' },
  },
  'speed-test-in-app': {
    en: { title: 'Using FollowNet Speed Test before you blame the VPN', excerpt: 'A short method: baseline without VPN, compare servers and protocols, and read results against your Free weekly limit.' },
    ru: { title: 'Speed Test в FollowNet: прежде чем винить VPN', excerpt: 'Короткий метод: baseline без VPN, сравнение серверов и протоколов, учёт недельного лимита Free.' },
    uk: { title: 'Використовуйте перевірку швидкості FollowNet, перш ніж звинувачувати VPN', excerpt: 'Короткий метод: базовий рівень без VPN, порівняння серверів і протоколів і зчитування результатів із вашим тижневим безкоштовним лімітом.' },
    de: { title: 'Verwenden Sie den FollowNet-Geschwindigkeitstest, bevor Sie dem VPN die Schuld geben', excerpt: 'Eine kurze Methode: Baseline ohne VPN, Server und Protokolle vergleichen und Ergebnisse mit Ihrem kostenlosen wöchentlichen Limit vergleichen.' },
    es: { title: 'Usando la prueba de velocidad de FollowNet antes de culpar a la VPN', excerpt: 'Un método breve: línea de base sin VPN, compare servidores y protocolos, y lea los resultados con respecto a su límite semanal gratuito.' },
    fr: { title: 'Utiliser FollowNet Speed ​​Test avant de blâmer le VPN', excerpt: 'Une méthode courte : référence sans VPN, comparez les serveurs et les protocoles et lisez les résultats par rapport à votre limite hebdomadaire gratuite.' },
    pt: { title: 'Usando o teste de velocidade FollowNet antes de culpar a VPN', excerpt: 'Um método curto: linha de base sem VPN, compare servidores e protocolos e leia os resultados em relação ao seu limite semanal gratuito.' },
  },
  'chrome-vs-ios-vpn': {
    en: { title: 'Chrome extension vs iOS VPN: same account, different jobs', excerpt: 'When to use FollowNet on iPhone system-wide and when the Chrome extension is enough for desktop browsing.' },
    ru: { title: 'Chrome extension vs iOS VPN: один аккаунт, разные задачи', excerpt: 'Когда нужен системный FollowNet на iPhone и когда хватает расширения Chrome для десктопного браузинга.' },
    uk: { title: 'Розширення Chrome проти iOS VPN: той самий акаунт, різні задачі', excerpt: 'Коли потрібен системний FollowNet на iPhone і коли вистачає розширення Chrome для десктопного браузингу.' },
    de: { title: 'Chrome-Erweiterung vs. iOS VPN: gleiches Konto, unterschiedliche Jobs', excerpt: 'Wann Sie FollowNet systemweit auf dem iPhone nutzen sollten und wann die Chrome-Erweiterung für Desktop-Surfen ausreicht.' },
    es: { title: 'Extensión de Chrome vs VPN para iOS: misma cuenta, diferentes trabajos', excerpt: 'Cuándo usar FollowNet en todo el sistema del iPhone y cuándo basta la extensión de Chrome para navegar en el escritorio.' },
    fr: { title: 'Extension Chrome vs VPN iOS : même compte, tâches différentes', excerpt: 'Quand utiliser FollowNet sur tout le système iPhone et quand l’extension Chrome suffit pour la navigation bureau.' },
    pt: { title: 'Extensão do Chrome vs VPN para iOS: mesma conta, trabalhos diferentes', excerpt: 'Quando usar o FollowNet em todo o sistema do iPhone e quando a extensão do Chrome basta para navegar no desktop.' },
  },
  'what-no-logs-means': {
    en: { title: 'Privacy and data in FollowNet: what to check beyond slogans', excerpt: 'A practical look at account data, analytics, DNS providers, and the limits of broad privacy claims.' },
    ru: { title: 'Приватность и данные в FollowNet: что проверять кроме слоганов', excerpt: 'Практичный разбор данных аккаунта, аналитики, DNS-провайдеров и границ широких заявлений о приватности.' },
    uk: { title: 'Конфіденційність і дані у FollowNet: що перевіряти, крім гасел', excerpt: 'Практичний погляд на дані акаунта, аналітику, постачальників DNS і межі широких заяв про приватність.' },
    de: { title: 'Datenschutz und Daten in FollowNet: Was Sie über Slogans hinaus prüfen sollten', excerpt: 'Ein praktischer Blick auf Kontodaten, Analysen, DNS-Anbieter und die Grenzen breiter Datenschutzversprechen.' },
    es: { title: 'Privacidad y datos en FollowNet: qué comprobar más allá de los eslóganes', excerpt: 'Una mirada práctica a los datos de cuentas, analítica, proveedores DNS y los límites de las afirmaciones amplias de privacidad.' },
    fr: { title: 'Confidentialité et données dans FollowNet : quoi vérifier au-delà des slogans', excerpt: 'Un regard pratique sur les données de compte, l’analytique, les fournisseurs DNS et les limites des grandes promesses de confidentialité.' },
    pt: { title: 'Privacidade e dados no FollowNet: o que conferir além dos slogans', excerpt: 'Uma visão prática dos dados da conta, analytics, provedores de DNS e os limites de promessas amplas de privacidade.' },
  },
  'app-store-vpn-review': {
    en: { title: 'Shipping a VPN through App Store review: constraints that shaped FollowNet', excerpt: 'Network Extension, entitlements, and review edges — why FollowNet stays an App Store native iOS client.' },
    ru: { title: 'VPN через App Store Review: ограничения, которые сформировали FollowNet', excerpt: 'Network Extension, entitlements и нюансы ревью — почему FollowNet остаётся нативным iOS-клиентом из App Store.' },
    uk: { title: 'Огляд доставки VPN через App Store: обмеження, які сформували FollowNet', excerpt: 'Розширення мережі, повноваження та переваги перегляду — чому FollowNet залишається рідним клієнтом iOS для App Store.' },
    de: { title: 'Überprüfung des Versands eines VPN über den App Store: Einschränkungen, die FollowNet geprägt haben', excerpt: 'Netzwerkerweiterung, Berechtigungen und Überprüfungsgrenzen – warum FollowNet ein nativer iOS-Client im App Store bleibt.' },
    es: { title: 'Envío de una VPN a través de la revisión de la App Store: limitaciones que dieron forma a FollowNet', excerpt: 'Extensión de red, derechos y márgenes de revisión: por qué FollowNet sigue siendo un cliente iOS nativo de la App Store.' },
    fr: { title: 'Examen de l\'expédition d\'un VPN via l\'App Store : les contraintes qui ont façonné FollowNet', excerpt: 'Extension réseau, droits et limites de révision : pourquoi FollowNet reste un client iOS natif de l\'App Store.' },
    pt: { title: 'Revisão do envio de uma VPN pela App Store: restrições que moldaram o FollowNet', excerpt: 'Extensão de rede, direitos e bordas de revisão – por que o FollowNet continua sendo um cliente iOS nativo da App Store.' },
  },
  'multi-device-premium': {
    en: { title: 'Premium across iPhone, iPad, and Chrome', excerpt: 'How FollowNet Premium follows your account — and what still differs per device.' },
    ru: { title: 'Premium на iPhone, iPad и в Chrome', excerpt: 'Как FollowNet Premium следует за аккаунтом — и что по-прежнему настраивается на каждом устройстве отдельно.' },
    uk: { title: 'Преміум для iPhone, iPad і Chrome', excerpt: 'Як FollowNet Premium стежить за вашим обліковим записом — і що все ще відрізняється для кожного пристрою.' },
    de: { title: 'Premium für iPhone, iPad und Chrome', excerpt: 'Wie FollowNet Premium Ihrem Konto folgt – und was je nach Gerät noch unterschiedlich ist.' },
    es: { title: 'Premium en iPhone, iPad y Chrome', excerpt: 'Cómo sigue FollowNet Premium su cuenta y qué difiere según el dispositivo.' },
    fr: { title: 'Premium sur iPhone, iPad et Chrome', excerpt: 'Comment FollowNet Premium suit votre compte – et ce qui diffère encore selon l\'appareil.' },
    pt: { title: 'Premium no iPhone, iPad e Chrome', excerpt: 'Como o FollowNet Premium acompanha sua conta — e o que ainda difere por dispositivo.' },
  },
  'when-vpn-wont-help': {
    en: { title: 'When a VPN will not help — honest limits for FollowNet users', excerpt: 'Encryption is powerful and finite. Cases where FollowNet cannot fix the underlying problem.' },
    ru: { title: 'Когда VPN не поможет — честные пределы FollowNet', excerpt: 'Шифрование сильно и конечно. Случаи, где FollowNet не чинит исходную проблему.' },
    uk: { title: 'Коли VPN не допоможе — чесні межі для користувачів FollowNet', excerpt: 'Шифрування потужне й кінцеве. Випадки, де FollowNet не лагодить вихідну проблему.' },
    de: { title: 'Wenn ein VPN nicht hilft – ehrliche Grenzen für FollowNet-Nutzer', excerpt: 'Verschlüsselung ist mächtig und endlich. Fälle, in denen FollowNet das eigentliche Problem nicht lösen kann.' },
    es: { title: 'Cuando una VPN no ayuda: límites honestos para usuarios de FollowNet', excerpt: 'El cifrado es poderoso y finito. Casos en los que FollowNet no puede arreglar el problema de fondo.' },
    fr: { title: 'Quand un VPN n’aide pas — limites honnêtes pour les utilisateurs FollowNet', excerpt: 'Le chiffrement est puissant et limité. Cas où FollowNet ne peut pas corriger le problème de fond.' },
    pt: { title: 'Quando uma VPN não ajuda — limites honestos para usuários FollowNet', excerpt: 'Criptografia é poderosa e finita. Casos em que o FollowNet não resolve o problema de fundo.' },
  },
  'follownet-roadmap-2026': {
    en: { title: 'FollowNet roadmap notes for 2026', excerpt: 'Where the product is headed: deeper iOS polish, Chrome parity where it matters, and protocols that survive real networks.' },
    ru: { title: 'Заметки о роадмапе FollowNet на 2026', excerpt: 'Куда движется продукт: глубже iOS, паритет Chrome где важно, протоколы, которые выживают в реальных сетях.' },
    uk: { title: 'Дорожня карта FollowNet на 2026 рік', excerpt: 'Куди прямує продукт: глибше вдосконалення iOS, паритет Chrome, де це важливо, і протоколи, які виживають у реальних мережах.' },
    de: { title: 'Hinweise zur FollowNet-Roadmap für 2026', excerpt: 'Wohin das Produkt geht: tiefere iOS-Verfeinerung, Chrome-Parität dort, wo es darauf ankommt, und Protokolle, die echte Netzwerke überleben.' },
    es: { title: 'Notas de la hoja de ruta de FollowNet para 2026', excerpt: 'Hacia dónde se dirige el producto: un pulido más profundo de iOS, paridad de Chrome donde importa y protocolos que sobrevivan a las redes reales.' },
    fr: { title: 'Notes de la feuille de route FollowNet pour 2026', excerpt: 'Vers où se dirige le produit : un peaufinage iOS plus approfondi, la parité Chrome là où cela compte et des protocoles qui survivent aux réseaux réels.' },
    pt: { title: 'Notas do roteiro da FollowNet para 2026', excerpt: 'Para onde o produto está indo: aprimoramento mais profundo do iOS, paridade do Chrome onde é importante e protocolos que sobrevivem a redes reais.' },
  },
  'censorship-networks-amneziawg': {
    en: { title: 'Restrictive networks and AmneziaWG: a field guide for FollowNet', excerpt: 'How DPI-shaped networks behave, when to try AmneziaWG or Hysteria2, and how Smart Connect fits without magic claims.' },
    ru: { title: 'Жёсткие сети и AmneziaWG: полевой гайд для FollowNet', excerpt: 'Как ведут себя сети с DPI, когда пробовать AmneziaWG или Hysteria2 и где место Smart Connect без магических обещаний.' },
    uk: { title: 'Обмежувальні мережі та AmneziaWG: польовий посібник для FollowNet', excerpt: 'Як поводяться мережі у формі DPI, коли спробувати AmneziaWG або Hysteria2 і як Smart Connect підходить без магічних претензій.' },
    de: { title: 'Restriktive Netzwerke und AmneziaWG: ein Leitfaden für FollowNet', excerpt: 'Wie sich DPI-förmige Netzwerke verhalten, wann man AmneziaWG oder Hysteria2 ausprobieren sollte und wie Smart Connect ohne Zaubersprüche funktioniert.' },
    es: { title: 'Redes restrictivas y AmneziaWG: una guía de campo para FollowNet', excerpt: 'Cómo se comportan las redes en forma de DPI, cuándo probar AmneziaWG o Hysteria2 y cómo encaja Smart Connect sin afirmaciones mágicas.' },
    fr: { title: 'Réseaux restrictifs et AmneziaWG : un guide de terrain pour FollowNet', excerpt: 'Comment se comportent les réseaux en forme de DPI, quand essayer AmneziaWG ou Hysteria2 et comment Smart Connect s\'intègre sans prétention magique.' },
    pt: { title: 'Redes restritivas e AmneziaWG: um guia de campo para FollowNet', excerpt: 'Como as redes em formato DPI se comportam, quando experimentar o AmneziaWG ou o Hysteria2 e como o Smart Connect se encaixa sem reivindicações mágicas.' },
  },
};

export function blogSeoMeta(slug: string, lang: AppLang): BlogSeoMeta | null {
  const block = BLOG_SEO[slug];
  if (!block) return null;
  return block[lang];
}
